language: julia

## https://docs.travis-ci.com/user/languages/julia
## If you leave the julia: key out of your .travis.yml, Travis CI will use the most recent release.
julia:
  - 1.0
  - nightly
os:
  - linux
  - osx
notifications:
  email: false

# script:
#   - julia -e 'using Pkg; Pkg.add("Documenter"); using KnetLayers, Documenter; cd(KnetLayers.dir("docs")); include("make.jl")'
allow_failures:
  - julia: 1.0
  - julia: nightly

after_success:
  - julia -e 'using Pkg; Pkg.add("Documenter"); using DPMM, Documenter; cd(KnetLayers.dir("docs")); include("make.jl")'
